#!/bin/bash
declare -i ID=$(cat backups/backup-id)
ID=$ID+1
cp -R bin backups/$ID-bin
cp -R _lib backups/$ID-_lib
cp -R lib backups/$ID-lib
cp -R presets backups/$ID-presets
echo "$ID">backups/backup-id
echo "
$ID-backup: $1">>backups/info.txt
exit
