#!/bin/bash
MAIN=$(pwd)
ARG1="$1"
ARG2="$2"
if [ $ARG1 ]; then
	ARG1="$1"
else
	ARG1="cello"
fi
if [ $ARG2 ]; then
	ARG2="$2"
else
	ARG2="0"
fi
cd $MAIN/scorefiles
echo "compiling $ARG1-$ARG2 in <scorefiles>"
lilypond $ARG1-$ARG2.ly
exit
