#!/bin/bash
ORIG="fullparts/original"
ALL="fullparts/*.ly"
mkdir $ORIG
cp $ALL $ORIG
echo "
*******
simplifying all rests in <$ALL>, putting backups in <$ORIG>...
"
perl  -0777 -i -pe 's/  r16  r16  r16  r16 /  r4 /igs' $ALL 
perl  -0777 -i -pe 's/  r16  r16 \n/  r8 \n/igs' $ALL 
perl  -0777 -i -pe 's/ \n  r16  r16 / \n  r8 /igs' $ALL 
perl  -0777 -i -pe 's/  r8  r16  r16 /  r4 /igs' $ALL
perl  -0777 -i -pe 's/  r16  r16  r8 /  r4 /igs' $ALL
perl  -0777 -i -pe 's/  r8  r8 /  r4 /igs' $ALL 
perl  -0777 -i -pe 's/  r8\.  r16 /  r4 /igs' $ALL 
perl  -0777 -i -pe 's/  r16  r8\. /  r4 /igs' $ALL 
perl  -0777 -i -pe 's/  r4 \n  r4 \n  r4 \n  r4 /  R1 /igs' $ALL 
perl  -0777 -i -pe 's/  r4 \n  r4 /  r2 /igs' $ALL 
perl  -0777 -i -pe 's/  r4\. \n  r8 /  r2 /igs' $ALL 
perl  -0777 -i -pe 's/  r8 \n  r4\. /  r2 /igs' $ALL 
perl  -0777 -i -pe 's/  r2 \n  r4 \n  r4 /  R1 /igs' $ALL 
perl  -0777 -i -pe 's/  r4 \n  r4 \n r2 /  R1 /igs' $ALL 
perl  -0777 -i -pe 's/  r4 \n  r2 \n r4 /  R1 /igs' $ALL 
perl  -0777 -i -pe 's/  r2\. \n  r4/  R1 /igs' $ALL 
perl  -0777 -i -pe 's/  r4 \n  r2\. /  R1 /igs' $ALL 
perl  -0777 -i -pe 's/  r2 \n  r2 /  R1 /igs' $ALL 
perl  -0777 -i -pe 's/  r4 \n  r2 \n  r4 /  R1 /igs' $ALL
perl  -0777 -i -pe 's/  r2 \n  r2 /  R1 /igs' $ALL
#take care of some simple barcheck fail on some rests
perl  -0777 -i -pe 's/ \:\n  r2 \n  r4  \|/ \:\n  R1 \|/igs' $ALL
perl  -0777 -i -pe 's/ \:\n  r4 \n  r2  \|/ \:\n  R1 \|/igs' $ALL
#an attempt to the \ottava lines
#perl  -0777 -i -pe 's/ / /igs' $ALL
echo "
*******
All rests were simplified!

Now, re-indenting and converting back to relative notation might take a while. Please, be patient...
"
ly -i "indent; abs2rel" $ALL
rm $ALL~
echo "
*******
Finished indenting and relative conversion.... Now, generate the scorefiles
*******
"
exit