#!/bin/bash
LILYPOND_VERSION=$(lilypond -v | head -n 1 | cut -d ' ' -f3-)
DIMENSION="$1"
if [ $DIMENSION]; then
	DIMENSION="$1"
else
	DIMENSION="17x11"
fi
echo "layout is $DIMENSION, feed me an argument to set up a new one"
mkdir scorefiles
for i in 0 1 2 3
do
echo "\\version \"$LILYPOND_VERSION\" " > scorefiles/fullscore-part-"$i".ly
echo "
\\include \"../fullparts/flute-part-$i.ly\"
\\include \"../fullparts/clarinet-part-$i.ly\"
\\include \"../fullparts/violin-part-$i.ly\"
\\include \"../fullparts/cello-part-$i.ly\"
\\include \"../fullparts/perc-part-$i.ly\"
\\include \"../lib/ottavate.ly\"
\\include \"../fullparts/pianoL-part-$i.ly\"
\\include \"../fullparts/pianoR-part-$i.ly\"

" >> scorefiles/fullscore-part-"$i".ly
PARTID=$(<lib/part-id.txt)
echo "
\\header {
title = \"a.le.a\"
subtitle = \"fullscore from meta-part $i - sco-$PARTID\"
composer = \"fdch\"
}
\\paper {
max-systems-per-page = #1
}
\\score {
<<
\set Score.skipBars = ##t
\\new Staff \\with { 
instrumentName = \"flute\" 
shortInstrumentName = \"fl.\"} 
{
<<
\\new Voice {
\\flute_one_part
}
>>
}
\\new Staff \\with { 
instrumentName = \"clarinet\" 
shortInstrumentName = \"cl.\"} 
{
<<
\\new Voice {
\\clarinet_one_part
}
>>
}
\\new Staff \\with { 
instrumentName = \"violin\" 
shortInstrumentName = \"vn.\"} 
{
<<
\\new Voice {
\\violin_one_part
}
>>
}
\\new Staff \\with { 
instrumentName = \"cello\" 
shortInstrumentName = \"vc.\"} 
{
<<
\\new Voice {
\\cello_one_part
}
>>
}
\\new Staff \\with { 
instrumentName = \"perc\" 
shortInstrumentName = \"perc.\"} 
{
<<
\\new Voice {
\\perc_one_part
}
>>
}
\\ottavate #'(2 . 7) #'(-5 . -6) ##t
\\new PianoStaff <<
\\set PianoStaff.instrumentName = #\"piano \"
\\set PianoStaff.shortInstrumentName = #\"pno.\"
\\new Staff = \"pianoL_one_part\" \\pianoL_one_part
\\new Staff = \"pianoR_one_part\" \\pianoR_one_part
>>

>>
\\layout {
\\mergeDifferentlyHeadedOn
\\mergeDifferentlyDottedOn
\\set Staff.pedalSustainStyle = #'mixed
#(set-default-paper-size \"$DIMENSION\")
}
}" >> scorefiles/fullscore-part-"$i".ly
done
echo "
*******
made all fullparts in <scorefiles>
*******
"
exit
